# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ff4oVemHDk1Nb7P1RFRt5JgguMln_ykU

day2
"""

class animal:
 def __init__(self, name) :
  self.name = name
 def eat (self) :
  print (f"{self.name} is eating")

 def sleep (self) :
   print (f"{self.name} is sleeping")


class dog (animal):
  def bark (self) :
    print (f"{self.name} is barking")


class cat (animal) :
  def meow (self) :
    print (f"{self.name} is meowing")

  dog= dog ("Sparky")
  cat= cat ("Tom")
  cat.meow()
  dog.bark()